[tool.poetry]
name = "ambiente-virtual"
version = "0.1.0"
description = ""
authors = ["clara <89088484+ClaraCosta@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
